version: '3.8'

services:
  mcp-omnisearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-omnisearch
    restart: unless-stopped
    ports:
      - "3000:3000"